use_sim_time: true
stance_leg_control_type: 1 # 0: QP; 1: MPC

# physics parameters

go1_robot_mass: 12.5

go1_trunk_inertia_xx: 0.0168128557
go1_trunk_inertia_xy: 0.0
go1_trunk_inertia_xz: 0.0
go1_trunk_inertia_yz: 0.0
go1_trunk_inertia_yy: 0.063009565
go1_trunk_inertia_zz: 0.0716547275

# default foothold position

go1_default_foot_pos_FL_x: 0.1881
go1_default_foot_pos_FL_y: 0.1300
go1_default_foot_pos_FL_z: -0.3200

go1_default_foot_pos_FR_x: 0.1881
go1_default_foot_pos_FR_y: -0.1300
go1_default_foot_pos_FR_z: -0.3200

go1_default_foot_pos_RL_x: -0.1881
go1_default_foot_pos_RL_y: 0.1300
go1_default_foot_pos_RL_z: -0.3200

go1_default_foot_pos_RR_x: -0.1881
go1_default_foot_pos_RR_y: -0.1300
go1_default_foot_pos_RR_z: -0.3200

go1_gait_counter_speed_FL: 1.5
go1_gait_counter_speed_FR: 1.5
go1_gait_counter_speed_RL: 1.5
go1_gait_counter_speed_RR: 1.5

# MPC parameters

# q_weights_0: 50.0 # roll
# q_weights_1: 100.0 # pitch
# q_weights_2: 0.0 # yaw

# q_weights_3: 0.0 # pos x
# q_weights_4: 0.0 # pos y
# q_weights_5: 3500.0 # pos z

# q_weights_6: 0.01 # omega x
# q_weights_7: 0.01 # omega y
# q_weights_8: 10.0 # omega z

# q_weights_9: 15.0 # vel x
# q_weights_10: 15.0 # vel y
# q_weights_11: 20.0 # vel z

# q_weights_12: 0.0

# r_weights_0: 0.0001
# r_weights_1: 0.0001
# r_weights_2: 0.0001

# r_weights_3: 0.0001
# r_weights_4: 0.0001
# r_weights_5: 0.0001

# r_weights_6: 0.0001
# r_weights_7: 0.0001
# r_weights_8: 0.0001

# r_weights_9: 0.0001
# r_weights_10: 0.0001
# r_weights_11: 0.0001

q_weights_0: 150.0 # roll
q_weights_1: 150.0 # pitch
q_weights_2: 50.0 # yaw

q_weights_3: 0.0 # pos x
q_weights_4: 0.0 # pos y
q_weights_5: 80.0 # pos z

q_weights_6: 0.2 # omega x
q_weights_7: 0.2 # omega y
q_weights_8: 0.2 # omega z

q_weights_9:  0.3 # vel x
q_weights_10: 0.3 # vel y
q_weights_11: 0.3 # vel z

q_weights_12: 0.0

r_weights_0:  1e-2
r_weights_1:  1e-2
r_weights_2:  1e-3

r_weights_3:  1e-2
r_weights_4:  1e-2
r_weights_5:  1e-3

r_weights_6:  1e-2
r_weights_7:  1e-2
r_weights_8:  1e-3

r_weights_9:  1e-2
r_weights_10: 1e-2
r_weights_11: 1e-3

# foot swing controller parameters
# force_tgt = km_foot * kp_foot * foot_pos_error

# go1_kp_foot_x: 200.0
#go1_kp_foot_x: 0.5
# go1_kp_foot_y: 200.0
#go1_kp_foot_y: 0.5
# go1_kp_foot_z: 150.0
#go1_kp_foot_z: 0.5

#go1_kd_foot_x: 0.3
#go1_kd_foot_y: 0.3
#go1_kd_foot_z: 0.3

#go1_km_foot_x: 0.1
#go1_km_foot_y: 0.1
#go1_km_foot_z: 0.1

go1_kp_foot_x: 120.0
go1_kp_foot_y: 120.0
go1_kp_foot_z: 80.0

go1_kd_foot_x: 6.0
go1_kd_foot_y: 6.0
go1_kd_foot_z: 5.0

go1_km_foot_x: 0.1
go1_km_foot_y: 0.1
go1_km_foot_z: 0.1
